// Copyright 2026 The go-ethereum Authors
// This file is part of the go-ethereum library.
//
// The go-ethereum library is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// The go-ethereum library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with the go-ethereum library. If not, see <http://www.gnu.org/licenses/>.

package core

import (
	"bytes"
	"fmt"
	"math/big"
	"testing"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/consensus/beacon"
	"github.com/ethereum/go-ethereum/consensus/ethash"
	"github.com/ethereum/go-ethereum/core/rawdb"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/crypto"
)

var (
	qualificationStoreAddr    = common.Address{0xba, 0x1e, 0x01}
	qualificationStoreRuntime = common.FromHex("0x60003560005500") // slot[0] = calldata[0:32]
)

func qualificationWord(n byte) []byte {
	word := make([]byte, 32)
	word[len(word)-1] = n
	return word
}

// balQualificationBlocks builds a deterministic chain whose state trajectory
// exercises the consequences that BAL-only reconstruction must preserve:
//
//   - storage set, overwrite, clear and rewrite
//   - multiple writes to the same slot in one block
//   - balance and nonce transitions from ordinary transfers
//   - contract creation/code installation
//   - an independently changing pre-deployed contract
//
// The chain is generated by canonical execution, so each block's BAL and state
// root are authoritative outputs of the normal execution path.
func balQualificationBlocks(t *testing.T) (*balTestEnv, []*types.Block, []common.Address) {
	t.Helper()

	env := newBALTestEnv(types.GenesisAlloc{
		counterAddr:             {Code: counterRuntime, Balance: common.Big0},
		qualificationStoreAddr: {Code: qualificationStoreRuntime, Balance: common.Big0},
	})
	engine := beacon.New(ethash.NewFaker())
	recipientA := common.Address{0xa1}
	recipientB := common.Address{0xb2}

	_, blocks, _ := GenerateChainWithGenesis(env.gspec, engine, 6, func(i int, b *BlockGen) {
		n := b.TxNonce(env.from)
		switch i {
		case 0:
			b.AddTx(balTx(t, env, n, &qualificationStoreAddr, common.Big0, qualificationWord(1)))
		case 1:
			b.AddTx(balTx(t, env, n, &qualificationStoreAddr, common.Big0, qualificationWord(2)))
			b.AddTx(balTx(t, env, n+1, &recipientA, big.NewInt(5_000_000_000), nil))
		case 2:
			// Clearing a previously non-zero slot is an important separator:
			// reconstruction must delete it rather than materialize zero.
			b.AddTx(balTx(t, env, n, &qualificationStoreAddr, common.Big0, qualificationWord(0)))
			b.AddTx(balTx(t, env, n+1, &counterAddr, common.Big0, nil))
		case 3:
			// Two writes in the same block ensure the final post-value wins.
			b.AddTx(balTx(t, env, n, &qualificationStoreAddr, common.Big0, qualificationWord(3)))
			b.AddTx(balTx(t, env, n+1, &qualificationStoreAddr, common.Big0, qualificationWord(4)))
		case 4:
			b.AddTx(balTx(t, env, n, nil, common.Big0, counterDeployer))
			b.AddTx(balTx(t, env, n+1, &recipientB, big.NewInt(7_000_000_000), nil))
		case 5:
			b.AddTx(balTx(t, env, n, &counterAddr, common.Big0, nil))
			b.AddTx(balTx(t, env, n+1, &qualificationStoreAddr, common.Big0, qualificationWord(5)))
		}
	})
	for _, block := range blocks {
		if block.AccessList() == nil {
			t.Fatalf("block #%d carries no access list", block.NumberU64())
		}
	}
	created := crypto.CreateAddress(env.from, blocks[4].Transactions()[0].Nonce())
	watched := []common.Address{
		env.from,
		counterAddr,
		qualificationStoreAddr,
		recipientA,
		recipientB,
		created,
	}
	return env, blocks, watched
}

func newBALQualificationChain(t *testing.T, env *balTestEnv, scheme string, reconstruct bool) *BlockChain {
	t.Helper()
	cfg := DefaultConfig()
	cfg.StateScheme = scheme
	cfg.BALStateReconstruction = reconstruct

	bc, err := NewBlockChain(
		rawdb.NewMemoryDatabase(),
		env.gspec,
		beacon.New(ethash.NewFaker()),
		cfg,
	)
	if err != nil {
		t.Fatalf("new blockchain (%s, reconstruct=%t): %v", scheme, reconstruct, err)
	}
	return bc
}

func assertBALQualificationStateEqual(t *testing.T, block *types.Block, canonical, reconstructed *BlockChain, watched []common.Address) {
	t.Helper()

	want, err := canonical.State()
	if err != nil {
		t.Fatalf("canonical state at block #%d: %v", block.NumberU64(), err)
	}
	got, err := reconstructed.State()
	if err != nil {
		t.Fatalf("reconstructed state at block #%d: %v", block.NumberU64(), err)
	}
	for _, addr := range watched {
		if want.Exist(addr) != got.Exist(addr) {
			t.Fatalf("block #%d account %s existence mismatch: canonical=%t reconstructed=%t",
				block.NumberU64(), addr, want.Exist(addr), got.Exist(addr))
		}
		if want.GetNonce(addr) != got.GetNonce(addr) {
			t.Fatalf("block #%d account %s nonce mismatch: canonical=%d reconstructed=%d",
				block.NumberU64(), addr, want.GetNonce(addr), got.GetNonce(addr))
		}
		if want.GetBalance(addr).Cmp(got.GetBalance(addr)) != 0 {
			t.Fatalf("block #%d account %s balance mismatch: canonical=%s reconstructed=%s",
				block.NumberU64(), addr, want.GetBalance(addr), got.GetBalance(addr))
		}
		if want.GetCodeHash(addr) != got.GetCodeHash(addr) {
			t.Fatalf("block #%d account %s code hash mismatch: canonical=%s reconstructed=%s",
				block.NumberU64(), addr, want.GetCodeHash(addr), got.GetCodeHash(addr))
		}
		if !bytes.Equal(want.GetCode(addr), got.GetCode(addr)) {
			t.Fatalf("block #%d account %s code mismatch", block.NumberU64(), addr)
		}
	}
	for _, addr := range []common.Address{counterAddr, qualificationStoreAddr} {
		key := common.Hash{}
		if want.GetState(addr, key) != got.GetState(addr, key) {
			t.Fatalf("block #%d account %s slot 0 mismatch: canonical=%s reconstructed=%s",
				block.NumberU64(), addr, want.GetState(addr, key), got.GetState(addr, key))
		}
	}
}

// TestBALReconstructionDifferential is the qualification oracle for the
// executionless finalized-state path. The same authoritative blocks are fed to
// two independent databases, one through normal execution and one through BAL
// reconstruction. After every block, all protected state observations must
// agree.
//
// Receipts are intentionally excluded from the equivalence relation: #35851
// explicitly defines reconstructed finalized blocks as receipt-less. The test
// asserts that boundary so future changes cannot accidentally blur it.
func TestBALReconstructionDifferential(t *testing.T) {
	for _, scheme := range []string{rawdb.HashScheme, rawdb.PathScheme} {
		t.Run(scheme, func(t *testing.T) {
			env, blocks, watched := balQualificationBlocks(t)

			canonical := newBALQualificationChain(t, env, scheme, false)
			defer canonical.Stop()
			reconstructed := newBALQualificationChain(t, env, scheme, true)
			defer reconstructed.Stop()

			for i, block := range blocks {
				if n, err := canonical.InsertChain([]*types.Block{block}); err != nil {
					t.Fatalf("canonical insert block #%d at index %d: inserted=%d err=%v", block.NumberU64(), i, n, err)
				}
				// Make exactly this block eligible for the finalized reconstruction
				// path before importing it.
				reconstructed.SetFinalized(block.Header())
				if n, err := reconstructed.InsertChain([]*types.Block{block}); err != nil {
					t.Fatalf("reconstructed insert block #%d at index %d: inserted=%d err=%v", block.NumberU64(), i, n, err)
				}

				canonHead := canonical.CurrentBlock()
				reconHead := reconstructed.CurrentBlock()
				if canonHead.Hash() != reconHead.Hash() || canonHead.Root != reconHead.Root {
					t.Fatalf("block #%d head mismatch: canonical=%s/%s reconstructed=%s/%s",
						block.NumberU64(), canonHead.Hash(), canonHead.Root, reconHead.Hash(), reconHead.Root)
				}
				assertBALQualificationStateEqual(t, block, canonical, reconstructed, watched)

				if receipts := canonical.GetReceiptsByHash(block.Hash()); len(receipts) != len(block.Transactions()) {
					t.Fatalf("block #%d canonical receipts=%d want=%d", block.NumberU64(), len(receipts), len(block.Transactions()))
				}
				if receipts := reconstructed.GetReceiptsByHash(block.Hash()); len(receipts) != 0 {
					t.Fatalf("block #%d reconstructed receipts=%d want=0", block.NumberU64(), len(receipts))
				}
			}

			// Make the final protected observations explicit in the failure name.
			state, err := reconstructed.State()
			if err != nil {
				t.Fatal(err)
			}
			if got := state.GetState(qualificationStoreAddr, common.Hash{}).Big().Uint64(); got != 5 {
				t.Fatalf("final qualification storage value=%d want=5", got)
			}
			if got := state.GetState(counterAddr, common.Hash{}).Big().Uint64(); got != 2 {
				t.Fatalf("final counter value=%d want=2", got)
			}
			t.Logf("BAL reconstruction qualified across %d sequential blocks (%s)", len(blocks), scheme)
		})
	}
}

func TestBALReconstructionQualificationCorpusDescription(t *testing.T) {
	// This tiny test keeps the intended corpus visible in test listings and CI
	// logs without introducing an external fixture format.
	t.Log(fmt.Sprintf("protected observations: account existence/balance/nonce/code, slot[0], state root; schemes=%s,%s",
		rawdb.HashScheme, rawdb.PathScheme))
}
